### ISSUE TITLE
HTTP Connection is not reused when polling feature flags

### ISSUE THREAD

**Issue by AdamGrzybkowski** [launchdarkly/android-client-sdk#110]
**Describe the bug**
I was profiling data usage of the app I'm working on and I found out that Launchdarkly is not reusing the HTTP connections. This means each connection needs to make a TLS handshake that increases the data usage significantly. 

**To reproduce**
Run the sample app and inspect the network.

**Expected behavior**
Lanuchdarkly should reuse the connection to optimize data usage.
It seems like the client is doing that but the server is not.

**Logs**
Here are the screenshots of two consecutive requests made by the SDK
| 1 | 2 |
|---|---|
| ![Zrzut ekranu 2020-10-1 o 09 38 11](https://user-images.githubusercontent.com/12660801/94781426-18d7b900-03ca-11eb-8e30-760c9d78060d.png) | ![Zrzut ekranu 2020-10-1 o 09 38 54](https://user-images.githubusercontent.com/12660801/94781810-a61b0d80-03ca-11eb-88ab-f5f7f3f5ae01.png) |

**SDK version**
2.13.0

**OS/platform**
Android 10

**Comment by gwhelanLD** [comment]
Hi @AdamGrzybkowski,

Since you indicate this seems to be a backend issue, rather than an issue with the SDK, could you [file this with our support team](https://support.launchdarkly.com/hc/en-us/requests/new)?

I'm going to close this issue, as it doesn't seem to apply directly to the SDK, but you can reopen this issue if you think the SDK should be doing something different here.

Thanks,
@gwhelanLD
