### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#123]
Last update was 3 months ago. We're paying for the service as a whole, and expect to see issues addressed, along with other improvements.

**Comment by bwoskow-ld** [comment]
Hi @valeriyo,

Yes, this project is maintained. Not only is the project maintained, but our SDK team has been hard at work completing some fairly large-impact changes for our upcoming version (3.0.0). Our internal development process isn't visible on this repository, as evidenced by the [`master` commit history](https://github.com/launchdarkly/android-client-sdk/commits/master), because we do all of our internal development on a private mirror of this repository. This is the case with all of LaunchDarkly's SDK repositories.

Admittedly we have slowed our cadence of releasing 2.x releases while focusing on the next major release, but this is somewhat intentional -- many of the changes requested by you or others on this repository's issue tracker are behaviorally breaking changes which we did not feel comfortable making in a minor version. We strongly believe in [semantic versioning](https://semver.org/) and try our best to adhere to it as noted in our [versioning policy](https://docs.launchdarkly.com/sdk/concepts/versioning). In addition to resolving many open requests, version 3.0.0 will have a clarify the delineation between APIs and internal details within the SDK, making it easier for our SDK team to move quickly for subsequent releases.

We're aware that we've been quietly working on 3.0.0 for some time now and are excited that we're _nearly_ ready to share it with you and the rest of our Android customer base. Stay tuned. I'll leave this issue open until the version is made available. If you want to further discuss maintenance and expectations around SDKs, you can reach out to your customer success manager (if your account has one), or to me personally at `ben<at>launchdarkly<dot>com`.

Cheers,
@bwoskow-ld

**Comment by bwoskow-ld** [comment]
Hi @valeriyo,

Thank you very much for your patience while we wrapped up work our latest major version. We're happy to announce that [version 3.0.0](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.0.0) of this SDK is now publicly available for use.

As noted in the lengthy release notes, _a lot_ of behind-the-scenes work went into this release on our private mirror in the lead-up towards the public release. We know that this isn't easily visible to the public, but, to re-iterate what I said earlier, this SDK is very much supported and we look forward to continuing to deliver a performant, reliable, feature-rich SDK to you and our other customers.

Cheers,
@bwoskow-ld
