### ISSUE TITLE
Is LD dead?

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#171]
Certainly appears so because issues are sitting for years unchecked.

**Comment by eli-darkly** [comment]
Clearly we're not dead, since there are recent issues that we have responded to within the last month. Older issues may or may not still be relevant, we do need to review and clean out things that have already been dealt with, but if there is a specific one you're concerned about could you please say what it is?

**Comment by eli-darkly** [comment]
Out of the oldest issues currently open, I can tell you off the top of my head:

* https://github.com/launchdarkly/android-client-sdk/issues/88 - using a different logging abstraction rather than Timber is a change we plan to include in the next major version release
* https://github.com/launchdarkly/android-client-sdk/issues/99 - I don't know if we were ever able to reproduce this; the original developer who replied is no longer with us, and I will check to make sure it didn't fall through the cracks
* https://github.com/launchdarkly/android-client-sdk/issues/102 - believed fixed, closed now
* https://github.com/launchdarkly/android-client-sdk/issues/108 - oh, I see, this is the issue you had in mind. You left an insulting comment as shown below, so I don't think you are probably still interested in a response.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/35503443/176572802-9d60b7d0-1753-40e6-b80a-a7b3b0118dad.png">

**Comment by eli-darkly** [comment]
I'll let others who are closer to the Android SDK project speak to the status of these issues. I know that we've had a heavy backlog for a while, due to a combination of short staffing for this particular project and prioritization of other areas of product work, but the Android SDK has still been in active development with multiple patch releases for other issues this year. That didn't include the issue that you were concerned with— probably because, based on the conversation so far, it was still not clear why this was as critical as you were saying it was (you did not say why you still needed to be able to reinitialize the SDK even though it has a multi-environment feature, and the other developer who commented seemed to have a fairly different use case). We still should have responded with a follow-up on that issue, I don't know how it fell through the cracks in this case, but insults won't fix that.
