### ISSUE TITLE
NPE on v5.3.0

### ISSUE THREAD

**Issue by rccl-pranit** [launchdarkly/android-client-sdk#270]
Hey LD Team,

I am facing a crash on launch after upgrading to v5.3.0.

**Logs**

```
Caused by:
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object
java.util.Map.get(java.lang.Object)'
on a null object reference at com.launchdarkly.sdk.android.LDClient.init(LDClient.java:248)
```

**SDK version**
v5.3.0

**Language version, developer tools**
Kotlin v1.7.20

**OS/platform**
Android

**Comment by tanderson-ld** [comment]
Hi @rccl-pranit, thank you for reporting this issue.  I have a few questions for you to help us track down the root cause and common-ness of encountering the issue.

1. What version were of the SDK were you upgrading from?
2. Do you call `LDClient.close()` anywhere in your code?  Just from looking at that line number, I think the only way `instances` is null is if close was called before `init(...)` .  I will have to do more investigation to verify expected behavior with respect to if the client can be re-init'd after close() if this theory is correct.
3. Were there any other changes to how your application populates LDContext attributes or perhaps how you handle login/logout flows and perhaps invoking `LDClient.identify(...)`?

**Comment by tanderson-ld** [comment]
4. Is this 100% reproducible?  If not, what portion of app launches do you see the issue?

**Comment by rccl-pranit** [comment]
@tanderson-ld here are the answers:
1. I am upgrading from v3.1.1 to v5.3.0
2. I am not calling `LDClient.close()` anywhere
3. Did not have to make any major changes while building `LDContext` & `LDConfig`
4. It crashes 100% of the time on fresh installs.

**Comment by rccl-pranit** [comment]
I did some digging and I think at some point `ContextKey` was made a required field [i.e. It cannot be null or empty], while for `LDUser` it was not. Maybe that is the reason I am getting this crash? Was not stated in any of the change logs.

**Comment by tanderson-ld** [comment]
Ahh, that is likely the root cause then.  We do have migration guides on our docs page that could be helpful to read through.  I believe this case is called out here: [Understanding changes to anonymous users](https://docs.launchdarkly.com/sdk/client-side/android/migration-3-to-4#understanding-changes-to-anonymous-users).

I should point out that Android has a config option for `generateAnonymousKeys`, while the iOS SDK will automatically do this if a context key is not provided.  We have it in our backlog to make Android consistent with iOS in this regard.

**Comment by rccl-pranit** [comment]
Understood. I must have missed the anonymous key gen part. Can you share the backlog ticket/issue number? so I can keep track of it.

**Comment by rccl-pranit** [comment]
Understood. I must have missed the anonymous key gen part. Can you share the backlog ticket/issue number? so I can keep track of it.

**Comment by tanderson-ld** [comment]
SC-245348 is the story.

Did setting the key end up resolving the issue?

**Comment by rccl-pranit** [comment]
Thank you @tanderson-ld! For now I have included a temp fix for it. But I will change it to iOS like implemented as soon as it is released.
