### ISSUE TITLE
Multiple instances of LDClient, a.k.a. using LD in a library?

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#90]
**Is your feature request related to a problem? Please describe.**
I'm building an app, and the core of the app is also shipped as a library to 3rd parties. If I use LD in the core - will it  interfere with 3rd party apps integrating my library? The documentation  (https://docs.launchdarkly.com/docs/android-sdk-reference#section-multiple-environments) claims that "LaunchDarkly's Android SDK supports having multiple LDClient instances tied to separate mobile keys" but then it also says "All LDClient instances will evaluate against the same LDUser." So, which is it? 

**Describe the solution you'd like**
I would like to create an instance of LDClient for use within my library, that wouldn't interfere with the rest of the app, which could be also using LD.

**Describe alternatives you've considered**
I am considering not using LD for feature flag, if it doesn't work in libraries.

**Additional context**
Documentation is lacking.

**Comment by bwoskow-ld** [comment]
Hello @valeriyo,

The functionality described in [our documentation](https://docs.launchdarkly.com/docs/android-sdk-reference#section-multiple-environments) allows for developers to use LaunchDarkly for _a single user across multiple LaunchDarkly projects/environments_. For example, it might be the case that a developer's LaunchDarkly account has one project named `core` for core (platform-agnostic) functionality, another project named `android` for their Android-specific functionality, and yet another project named `ios` for their iOS-specific functionality. In this example, the developer might want their Android app to evaluate flags in both the `core` and `android` projects -- this is possible through the use of the documented feature. Similar to all of our client-side SDKs, these SDKs are meant to be used for a single user context at a time, regardless of if a single environment or multiple are configured. You can read more about this in [our documentation](https://docs.launchdarkly.com/docs/client-side-and-server-side#section-understanding-the-different-types-of-sdks).

My understanding of your use case is that your customers might want to use your library's LaunchDarkly flags as well as any of their own LaunchDarkly flags. Will there be a single, consistent user across these two areas? If so, this is supported as described above.

Let me know if this answers your question. To get further help using the Android SDK, feel free to reach out to our support team at support@launchdarkly.com.

**Comment by valeriyo** [comment]
Not what I was asking. Let's try again: I would like to create an instance of LDClient for use within my library, that wouldn't interfere with the rest of the app, which could be also using LD.

**Comment by bwoskow-ld** [comment]
The SDK isn't designed to have multiple instances running within a single app. Your library's customers would have two copies of the SDK client -- both of which use the same classes and a shared static instance. They'd fight over configuring the client and it would only work for one of the two uses.

One potential workaround might be for you to shade the LaunchDarkly SDK in your core so that its LaunchDarkly client instance is independent from your customers' apps' instances. This workaround technically isn't supported but it might just work. Note that, for customers using LaunchDarkly and your library, this workaround would impose that they consume double the resources -- twice the connections and dex count in addition to whatever extra memory is utilized for flags and events.

Another option would be for you to add a facade layer around the LDClient in your core code such that, when called within your own application the LDClient is utilized but when called as a lib then the code short-circuits and just returns a hard-coded value instead of using LaunchDarkly. Adding a facade layer like this would allow you to gain the benefits of using LaunchDarkly in your core code without forcing problems onto customers using your lib.

I believe that this sufficiently answers your question; feel free to comment again and/or re-open if you want to discuss further.
