### ISSUE TITLE
NullPointerException when passing null as the fallback value of jsonVariation

### ISSUE THREAD

**Issue by justinJobox** [launchdarkly/android-client-sdk#97]
**Describe the bug**
Upgraded LaunchDarkly to 2.10.0 from an older version, once the app is updated from Google Play store, the app will crash 1-2 times due to this line:
`LDClient.jsonVariation(FLAG_KEY, null)`

**Logs**
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
       at com.launchdarkly.android.UserSummaryEventSharedPreferences.addOrUpdateEvent(UserSummaryEventSharedPreferences.java:49)
       at com.launchdarkly.android.LDClient.updateSummaryEvents(LDClient.java:630)
       at com.launchdarkly.android.LDClient.variationDetailInternal(LDClient.java:394)
       at com.launchdarkly.android.LDClient.jsonVariation(LDClient.java:353)`

**SDK version**
Android sdk 2.10.0

**Language version, developer tools**
Kotlin, Android Studio

**OS/platform**
Android

**Comment by gwhelanLD** [comment]
Hi @justinJobox,

Thanks for reporting this issue. Could you respond with what version you're updating from to help us narrow down this issue?

Thanks,
@gwhelanLD

**Comment by justinJobox** [comment]
@gwhelanLD `2.5.1`

**Comment by mahmoudfath** [comment]
Any update on this issue I'm facing the same

**Comment by gwhelanLD** [comment]
Hi @mahmoudfath,

We should have a fix out in the next release. This issue occurs when the fallback is null and there is not a flag value for the flag being evaluated (doesn't exist or the SDK has not received it yet). This is why you would not necessarily see this issue in testing. In the meantime, a temporary workaround would be to use an alternative fallback value instead of null. As long as that value is still distinguishable from an actual flag target, you would still be able to detect whether the flag was received or not.

We'll update this issue when the fix is out.
Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
The fix for this is out in the [2.12.0](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.12.0) release. Thanks for your patience on this issue.
